version: '3'

networks:
  default:
    driver: bridge

services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    restart: always
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    depends_on: 
      - mysql 
    networks: 
      - default 

  mysql:
    image: mysql
    restart: always
    volumes:
      - /home/bekzad/Public/all-projects/yii2-test/data/:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=112233
      - MYSQL_DATABASE=db
      - MYSQL_USER=atlogex
      - MYSQL_PASSWORD=123456
    ports:
      - "3000:3306"
    networks:
      - default
