version: '3'

services:
  nginx:
    container_name: ${APP_ID}-nginx-container
    image: nginx:1.14
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx-${MODE}.conf:/etc/nginx/nginx.conf
    depends_on:
      - php

  php:
    container_name: ${APP_ID}-php-container
    build:
      context: ./docker/php-fpm
      args:
        GITHUB_AUTH_TOKEN: ${GITHUB_AUTH_TOKEN}
    restart: always
    volumes:
      - ./:/var/www/html

#  db:
#    image: mariadb
#    container_name: ${APP_ID}-db
#    environment:
#      - MARIADB_USER=${DB_USER}
#      - MARIADB_PASSWORD=${DB_PASSWORD}
#      - MARIADB_DB=${DB_NAME}
#      - MARIADB_ROOT_PASSWORD=root
#    ports:
#      - 3306:3306

networks:
  default:
    external:
      name: ${DOCKER_NETWORK}